# Generated by Django 5.2.13 on 2026-06-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_0', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
