# Generated by Django 5.2.13 on 2026-06-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_0', '0002_userregister_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
